name       : deepin-clutter
version    : 1.26.2
release    : 1
source     :
    - https://github.com/sonald/clutter/archive/1.26.2.tar.gz : 08cc169af09b89a4fb09c38fa5732d7995f73f865783882f2bf91423830d97ba
license    : LGPL-2.1-or-later
component  : desktop.deepin.core
conflicts  :
    - clutter
summary    : Deepin fork of clutter.
description: |
    Deepin fork of clutter.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo-gobject)
    - pkgconfig(gdk-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libinput)
    - pkgconfig(pangocairo)
    - deepin-cogl-devel
    - gtk-doc
setup      : |
    %autogen --disable-static \
             --enable-egl-backend \
             --enable-evdev-input \
             --enable-gdk-backend \
             --enable-gdk-pixbuf \
             --enable-introspection \
             --enable-wayland-backend \
             --enable-wayland-compositor \
             --enable-x11-backend \
             --enable-xinput
build      : |
    export PYTHONIOENCODING=utf-8
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
