name       : deepin-account-faces
version    : 1.0.11
release    : 14
source     :
    - git|https://github.com/linuxdeepin/dde-account-faces.git : 1.0.11
license    : CC0-1.0
component  : desktop.deepin.core
summary    : Account faces for Linux Deepin
description: |
    Account faces for Linux Deepin
build      : |
    %make
install    : |
    %make_install
