name       : deepin-qt5integration
version    : 5.0.0
release    : 37
source     :
    - git|https://github.com/linuxdeepin/qt5integration.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Qt platform theme integration plugins for DDE
description: |
    The Qt platform theme integration plugins for Deepin Desktop Environment. It includes multiple Qt5 plugins to make make DDE more Qt5 Apps friendly.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(mtdev)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Xdg)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
