#!/bin/bash
# Removing pspec.xml files
find . -iname "pspec*.xml" -type f -exec rm -rf {} \;
# Removing abi symbol files
find . -iname "abi_used_libs" -type f -exec rm -rf {} \;
# Removing eopkgs
find . -iname "*.eopkg" -type f -exec rm -rf {} \;
rm -f success failures