name       : deepin-editor
version    : 1.2.9.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-editor.git : 1.2.9.1
license    : GPL-3.0-or-later # -or-later assumed from other projects
component  : desktop.deepin
summary    : Deepin Editor.
description: |
    Deepin Editor: simple editor for deepin.
builddeps  :
    - kcodecs-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
    - pkgconfig(xtst)
    - qt5-tools-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
