name       : dpa-ext-gnomekeyring
version    : 5.0.1
release    : 1
source     :
    - https://github.com/linuxdeepin/dpa-ext-gnomekeyring/archive/5.0.1.tar.gz : 75fb1acd82c8018931735dad0c7e27933c15eb251b49c1e24dda793f77cf0746
license    : GPL-2.0-or-later # CHECK ME
component  : desktop.deepin
summary    : Deepin Polkit Agent - GNOME Keyring Extension
description: |
    Deepin Polkit Agent - GNOME Keyring Extension
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - deepin-polkit-agent-devel
setup      : |
    %qmake
build      : |
    %make
install    : |
    make INSTALL_ROOT=%installroot% install
