name       : deepin-music
version    : 5.0.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-music.git : 5.0.1
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : Music player for the Deepin DE
description: |
    Deepin Music is an application developed by Deepin Technology Team which focused on local music playing. It brings all brand new UI design, extreme playing experience, and it has local music scanning and lyric sync functions, etc.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(icu-uc)
    - pkgconfig(libavcodec)
    - pkgconfig(libavformat)
    - pkgconfig(libavutil)
    - pkgconfig(libcue)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(taglib_c)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
