name       : deepin-clutter-gtk
version    : 1.8.4
release    : 1
source     :
    - https://download.gnome.org/sources/clutter-gtk/1.8/clutter-gtk-1.8.4.tar.xz : 521493ec038973c77edcb8bc5eac23eed41645117894aaee7300b2487cb42b06
license    : LGPL-2.0-only
component  : desktop.deepin.core
conflicts  :
    - clutter-gtk
summary    : Clutter GTK+ API, build for Deepin
description: |
    Clutter GTK+ API, build for Deepin
builddeps  :
    - deepin-clutter-devel
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --enable-introspection
build      : |
    %make
install    : |
    %make_install
