name       : dtkcore
version    : 2.1.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/dtkcore.git : 2.1.1
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Deepin Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer
    work on Deepin.
description: |
    Deepin Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - pkgconfig(gsettings-qt)
    - qt5-base-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
