name       : perl-config-tiny
version    : 2.23
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RS/RSAVAGE/Config-Tiny-2.23.tgz : 9a8a66e3ed420cbc6585c43abeff788368309a46355cf69a64c2a47e1911e50c
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Read/Write .ini style files with as little code as possible.
description: |
    Read/Write .ini style files with as little code as possible.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
