name       : deepin-image-viewer
version    : 1.3.18
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-image-viewer/archive/1.3.18.tar.gz : 4c615922fd972ddb8662b5000e9fdd7310d89d9511dfa2fdfe38551117dbea3e
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : Deepin Desktop Environment Image Viewer.
description: |
    Deepin Image Viewer is Deepin Desktop Environment Image Viewer.
builddeps  :
    - freeimage-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(libexif)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
    - freeimage-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir% QMAKE_CFLAGS_ISYSTEM=
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
