name       : deepin-file-manager
version    : 5.0.0
release    : 48
source     :
    - git|https://github.com/linuxdeepin/dde-file-manager.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    :
    - Deepin File Manager is a file management tool developed for Deepin
description:
    - Deepin File Manager is a file management tool independently developed by Deepin
      Technology, featured with searching, copying, trash, compression/decompression,
      file property and other file management functions.
builddeps  :
    - deepin-anything-devel
    - deepin-dock-devel
    - deepin-gettext-tools
    - kcodecs-devel
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gsettings-qt)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jemalloc)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libdmr)
    - pkgconfig(libsecret-1)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(poppler-cpp)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(taglib)
    - pkgconfig(uchardet)
    - pkgconfig(xcb-ewmh)
    - qt5-tools-devel
rundeps    :
    - avfs
    - deepin-qt5integration
    - treefrog-framework
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
