name       : deepin-introduction
version    : 5.0.0
release    : 25
source     :
    - git|https://github.com/linuxdeepin/dde-introduction.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Introduction for deepin
description: |
    Deepin initialization setup tool
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(libdmr)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(dtkwidget)
    - pkgconfig(Qt5Multimedia)
    - qt5-tools-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
