name       : deepin-polkit-agent
version    : 5.0.0
release    : 25
source     :
    - git|https://github.com/linuxdeepin/dde-polkit-agent.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop
summary    : Deepin Polkit Agent
description: |
    Deepin Polkit Agent
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(polkit-qt5-1)
    - qt5-tools-devel
setup      : |
    sed -i 's|dcombobox.h|QComboBox|' AuthDialog.h
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
