name       : deepin-gir-generator
version    : 2.0.2
release    : 22
source     :
    - git|https://github.com/linuxdeepin/go-gir-generator.git : 2.0.2
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Static golang bindings for GObject.
description: |
    Static golang bindings for GObject.
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/SettingsBackendLike.patch
    %patch -p1 < $pkgfiles/0001-Makefile-Make-directory.patch
build      : |
    export GOPATH="${workdir}"
    %make
install    : |
    %make_install
