dictionary:
  - name      : deepin-network-utils-devel
    pkgconfigs:
        - dde-network-utils
  - name      : deepin-qt-dbus-factory-devel
    pkgconfigs:
        - dframeworkdbus
  - name      : dtkcore-devel
    pkgconfigs:
        - dtkcore
  - name      : dtkwidget-devel
    pkgconfigs:
        - dtkwidget
  - name      : dtkwm-devel
    pkgconfigs:
        - dtkwm
  - name      : geoip-devel
    pkgconfigs:
        - geoip
  - name      : gsettings-qt-devel
    pkgconfigs:
        - gsettings-qt
  - name      : deepin-mutter-devel
    pkgconfigs:
        - libdeepin-mutter
  - name      : deepin-movie-devel
    pkgconfigs:
        - libdmr
  - name      : liblightdm-qt5-devel
    pkgconfigs:
        - liblightdm-qt5-3
  - name      : libmongoc-devel
    pkgconfigs:
        - libmongoc-1.0
  - name      : libqtxdg-devel
    pkgconfigs:
        - Qt5Xdg
  - name      : udisks2-qt5-devel
    pkgconfigs:
        - udisks2-qt5