name       : deepin-terminal
version    : 5.0.0
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-terminal.git : 98b119bbc875570f38b2377a713e0ecb5ddb291e
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : This is default terminal emulation application for Deepin.
description: |
    This is default terminal emulation application for Deepin.
builddeps  :
    - gperf
    - pkgconfig(gee-0.8)
    - pkgconfig(glib-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpcre2-8)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(vte-2.91)
    - vala
rundeps    :
    - deepin-menu
    - expect
setup      : |
    %patch -p1 < $pkgfiles/0001-CMakeLists-Remove-specific-Glib-version.patch
    mkdir build
    pushd build
    %cmake .. -DTEST_BUILD=OFF \
              -DUSE_VENDOR_LIB=OFF \
              -DCMAKE_INSTALL_PREFIX=/usr \
              -DCMAKE_BUILD_TYPE=Release \
              -DVERSION=$version
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
