name       : qt5-xcb-private-headers
version    : 5.12.6
release    : 16
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.6/submodules/qtbase-everywhere-src-5.12.6.tar.xz : 533078ce02678988576e224cb3844979907950cf83e0fda3364bc1d5701c9049
license    :
    - FDL-1.3
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Private headers for Qt5 Xcb
description: |
    Private headers for Qt5 Xcb
rundeps    :
    - qt5-base
install    : |
    install -d -m0755 "${installdir}/usr/include/qtxcb-private"
    cp -r src/plugins/platforms/xcb/*.h "${installdir}/usr/include/qtxcb-private/"
