name       : deepin-dbus-factory
version    : 3.1.17
release    : 1
source     :
    - git|https://github.com/linuxdeepin/dbus-factory.git : 3.1.17
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : GO DBus factory for Deepin
description: |
    GO DBus factory for Deepin
builddeps  :
    - deepin-dbus-generator
    - jq
build      : |
    %make
install    : |
    %make_install GOPATH=/usr/share/gocode
