name       : startdde
version    : 5.0.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/startdde.git : 5.0.1
networking : yes
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Starter of deepin desktop environment
description: |
    Launches Deepin Desktop Envrionment components and invoking user's custom applications which compliant with xdg autostart specification.
builddeps  :
    - deepin-api
    - deepin-dbus-factory
    - deepin-gir-generator
    - deepin-go-dbus-factory
    - deepin-go-lib
    - git
    - golang
    - jq
    - pkgconfig(alsa)
    - pkgconfig(gdk-3.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libpulse-simple)
    - pkgconfig(x11)
    - pkgconfig(xi)
rundeps    :
    - deepin-control-center
    - deepin-daemon
    - deepin-desktop
    - deepin-dock
    - deepin-gtk-theme
    - deepin-icon-theme
    - deepin-icon-theme-dark
    - deepin-icon-theme-sea
    - deepin-launcher
    - deepin-polkit-agent
    - deepin-session-ui
    - deepin-sound-theme
    - deepin-wm-switcher
setup      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    mkdir -p "${workdir}/src/pkg.deepin.io/dde/"
    ln -s "${workdir}/" "${workdir}/src/pkg.deepin.io/dde/startdde"
    go get github.com/cryptix/wav
    go get github.com/BurntSushi/xgb
    go get github.com/BurntSushi/xgbutil
    go get github.com/linuxdeepin/go-x11-client
    go get golang.org/x/net/context
build      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    %make
install    : |
    %make_install
