name       : imwheel
version    : 1.0.0_pre12
release    : 12
source     :
    - https://sourceforge.net/projects/imwheel/files/imwheel-source/1.0.0pre12/imwheel-1.0.0pre12.tar.gz/download : 2320ed019c95ca4d922968e1e1cbf0c075a914e865e3965d2bd694ca3d57cfe3
license    : GPL-2.0-only
component  : system.utils
summary    : A tool for tweaking mouse wheel behavior
description: |
    imwheel is a tool for tweaking mouse wheel behavior, on a per-program basis. It can map mousewheel input to keyboard input, increase mousewheel speed, and has support for modifier keys.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmu)
    - pkgconfig(xtst)
setup      : |
    %patch -p1 < $pkgfiles/destdir.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
