name       : deepin-daemon
version    : 3.23.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/dde-daemon.git : 3.23.1
networking : yes
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Daemon handling the DDE session settings
description: |
    Daemon handling the DDE session settings
builddeps  :
    - deepin-api
    - deepin-dbus-factory
    - deepin-gettext-tools
    - deepin-gir-generator
    - deepin-go-dbus-factory
    - deepin-go-lib
    - git
    - golang
    - pkgconfig(alsa)
    - pkgconfig(gdk-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libinput)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libpulse-simple)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libudev)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
rundeps    :
    - deepin-desktop-schemas
    - deepin-notifications
    - dnsmasq
    - gnome-keyring
    - network-manager
    - polkit-gnome
    - udisks
    - upower
    - xdotool
    - xorg-driver-input-wacom
setup      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    # Some symlink fuckery because their servers were down at the time, and it
    # avoids redownloading.
    mkdir -p "${workdir}/src/pkg.deepin.io/dde/"
    ln -s "${workdir}/" "${workdir}/src/pkg.deepin.io/dde/daemon"
    %patch -p1 < $pkgfiles/dde-daemon_3.8.0.patch
    go get github.com/axgle/mahonia
    go get github.com/BurntSushi/freetype-go/freetype/truetype
    go get github.com/BurntSushi/graphics-go/graphics
    go get github.com/BurntSushi/xgb
    go get github.com/BurntSushi/xgbutil
    go get github.com/cryptix/wav
    go get github.com/linuxdeepin/go-x11-client
    go get github.com/msteinert/pam
    go get github.com/nfnt/resize
    go get golang.org/x/image/bmp
    go get golang.org/x/image/tiff
    go get golang.org/x/net/context
    go get golang.org/x/text/encoding/charmap
    go get gopkg.in/alecthomas/kingpin.v2
build      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    %make
install    : |
    %make_install
    install -Dm0644 $pkgfiles/deepin-daemon.sysusers "$installdir/%libdir%/sysusers.d/deepin-daemon.conf"
