name       : deepin-voice-recorder
version    : 5.0.0
release    : 23
source     :
    - git|https://github.com/linuxdeepin/deepin-voice-recorder.git : 5.0.0
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : Default voice recorder application for Deepin.
description: |
    Deepin Voice Recorder is a beautiful and easy to use voice recording application with simple design. No matter recording your singing, phone call or meeting conversation, you can finish all these tasks by Deepin Voice Recorder. It also supports visual recording, recording playback, recording list management and other functions.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(libavformat)
    - pkgconfig(Qt5Multimedia)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
